### ISSUE TITLE
Levantamento de Requisitos

### ISSUE THREAD

**Issue by VictorKoehler** [DefinitelyNotACactus/Numberphy#12]
Verificar a necessidade de aderir novas bibliotecas de terceiros, principalmente considerando as necessidades dos trabalhos a longo prazo. ~Por favorzinho, nada de bibliotecas antigas e exóticas feitas em AWT ou outras bizarrices dificeis de debugar.~

**Comment by DefinitelyNotACactus** [comment]
Não foi necessário utilizar nenhuma biblioteca adicional para a implementação dos métodos de Interpolação.
