### ISSUE TITLE
Resolver redimensionamento

### ISSUE THREAD

**Issue by DefinitelyNotACactus** [DefinitelyNotACactus/Numberphy#5]

**Comment by VictorKoehler** [comment]
O Zoom Out já existe na biblioteca, apesar de obscuro.
Basta segurar o SHIFT e clicar com o mouse. (Clique único e singular)
Se quiserem, podemos reabrir o issue para a implementação do zoom com o Scroll do mouse (é possível mas recomendo deixar para depois que terminarmos o urgente)
