### ISSUE TITLE
Adicionar readme

### ISSUE THREAD

**Issue by DefinitelyNotACactus** [DefinitelyNotACactus/Numberphy#7]

**Comment by VictorKoehler** [comment]
Galvão, você vai fazer isso ou vai deixar para outra pessoa, por exemplo, Piu?

**Comment by DefinitelyNotACactus** [comment]
Pretendo formatar e adaptar o que já existe em HalleyDescription e RiddersDescription, provavelmente não caberá a mim preencher o readme com conteúdo.
